[project]
name = "pythonrefresher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tusharpatgar", email = "117505866+tusharpatgar@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pythonrefresher = "pythonrefresher:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
